sudo: required

services:
  - docker

env:
  global:
    - PATH="${PATH}:${HOME}/.local/bin"
    - AWS_DEFAULT_REGION="eu-central-1" TARGET_ECS_CLUSTER="ecs-delivery-EcsCluster-RB5CTHWH6SW6"
    - secure: EnUEHszRMDqAh2gbAbU5j4M2DGT08apGXCBmCegt12kszR2oIMZ+lTPYXhVN4TM8LnooMwASkKyutJxeXF4THUvY7LW1s1yqOLUMXO+WkjqL+TM0sT1Elvw87c418Y0OAFun9j79AUHn21s1v+QjjIxMd0nZq5VsLzvOctbicQky335ypX+PZft15rukFZs8n08zllZ+raBEMWJGfHi9TTAIv6wkEtZrTMu1Rn8famx9P+D6yJZ3NgejJpDBx8/N7YTpcqIMcY0ezVHWFsuhu6Bv0nfsG/g/3TEB6sU8n9sUtaPajEZm26J/QGvNhyIZkWcDQy8Q9CpgM+i43q0Wre8izJiXq1EFS7HTNF9WWgIDoN5oONzJEuZLXbBmtPUGFoJ06RQbV1QCpbHzAMdfwyEQk9+ckesI2BxWNca1iHydPJCR64/pBsDFc0DeyvQcB8/fMOHyD1D0U+n7y4ZIOZFRmZmcKDIIS7mDMT1e/JZ7I7Z1nuPHrcjCus4gV/QqaGJmaZgkEEbfKvGtD9mW1ajv9OMi5oG32OaeSBknfpDUahxtw760lxs2FLrBAFKjIdMch3Fgm3fkl4xVGItUj7J9Ymdg9S3aNM1CZ9xlHV3e05OgSpE5A3EuqDIWI9N91MIdtAAzib1j9t1dFWhtc9Y+m0jD7DhMDF3ksBFonrI=
    - secure: Ty+Og8WWV94hniKPvwZZtu5U8LRgSWBqmJPJWPTHO4PgDBFITs343XCV5vE0FBFsANpdKBrwnxtlh3W9xSFvuz7/khtUfzV+fRg4tP1rRohglQ147Go1tqayVMZF6ZeypSXUWvETnq7MBoNVUDKlt8KbYbfejDoERaHe+qRsofTnLY9kY0yR/boouT8+T3ZUONOUjHt5IXPhNVXzV6htkwf5Fm+46VZbilu/f2qMOb9NCyQtvCm6FKwR8IxbTxY2V83V8NoOPwDgVn9oEpDzqZJcUfAv2wERwDV+p+FpOmICL8i+x5aQ5KwwnWn2RStjsoi9sXvkICFQNH7LsLx65UY+Rub5WWLvyf9yjnyyNhKZwbyYbdaimrAkTnGJn6qDC/aLp34+2cuiokvCNj5PpRUpvWCosU27IE5d0kHPsulfdXCDsxaBawR1aPoSN9FCPjqF9tWuOrmdmbByYK7FE3/lpCMvW7N8bE+94WYSzbLTgij5fhIQyHacgKVQR96Txe+5SfAKlLJkCGE+Q+0KPMo0V4Wfa6UJGMcgaNXl+HOhS/T5BfyPmkIBzHalJzCpsp2wn0iLLEYT++4aRxLq3hNfIHqP3uebqhuc7b747auf79QrLHR0N3fPV8Dg3ZxMyZeviDr/hWXuHNhyghq2RcayehANCVcDiBsPcFgX1+s=
  
install:
  - pip install --user awscli

script:
  - docker version
  - docker images
  - ./tools/build
  - docker images

after_success:
  - docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - ./tools/deliver $TARGET_ECS_CLUSTER
