#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

cluster=$1

ecs() {
  aws --profile weaveworks ecs $@
}

service_is_missing() {
  ecs describe-services \
      --cluster ${cluster} \
      --services "${name}-service" \
    | jq -r '.failures[0].reason' \
    | grep -q MISSING 
}

ecs list-task-definition-families

for app in $(ls app-services/*.json) ; do
  name=$(basename ${app} .json)

  ecs register-task-definition \
      --family "${name}-task" \
      --container-definitions "$(jq -c '.containers' ${app})" \
    | jq .
  
  if service_is_missing ; then
    ecs create-service \
        --cluster ${cluster} \
        --service-name "${name}-service" \
        --task-definition "${name}-task" \
        --cli-input-json "$(jq -c '.service' ${app})" \
      | jq .
  else
    ecs update-service \
        --cluster ${cluster} \
        --service "${name}-service" \
        --task-definition "${name}-task" \
        --cli-input-json "$(jq -c '.service' ${app})" \
      | jq .
  fi
done
